<?php
// module/cinema/view/cinema/cinema/edit.phtml:

$title = 'Edit cinema';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

// This provides a default CSS class and placeholder text for the artist element:
$ownerId = $form->get('ownerId');
$ownerId->setAttribute('class', 'form-control');
$ownerId->setAttribute('placeholder', 'Owner');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('cinema', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($ownerId) ?>
    <?= $this->formElement($ownerId) ?>
    <?= $this->formElementErrors()->render($ownerId, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();