
<?php
$title = 'Movies';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<div class="form-group">
    <input type="text" name="title" class="form-control" placeholder="Movie title" value="Test21">    
</div>

<table class="table">
<tr>
    <th><?php if ($this->auth()->isAllowed('movie_edit')) { ?>

    <a href="<?php echo $this->url('movie', array('action'=>'add'));?>">
        <img src="<?= $this->basePath('img/add.jpg') ?>" height="26" alt="Add"/>
    </a>
<?php } ?></th>
    <th>Title</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Cinema name</th>
    <th>Category</th>
    <?php if ($this->auth()->isAllowed('movie_edit')) { ?>
    <th>&nbsp;</th>
    <?php } ?>
</tr>
<?php foreach ($movies as $movie) : ?>
<tr>
    <td>
        <?php if (in_array($movie->id, $favourites)) { ?>
            <a href="<?php echo $this->url('movie',
            array('action'=>'unfavourite', 'id' => $movie->id));?>">
            <img src="<?= $this->basePath('img/yellow_star.jpg') ?>" height="20" alt="Edit"/>
        </a>
        <?php } else { ?>
            <a href="<?php echo $this->url('movie',
            array('action'=>'favourite', 'id' => $movie->id));?>">
            <img src="<?= $this->basePath('img/black_star.jpg') ?>" height="20" alt="Edit"/>
        </a>
        <?php } ?>
    </td>
    <td><?php echo $this->escapeHtml($movie->title);?></td>
    <td><?php echo $this->escapeHtml($movie->startDate);?></td>
    <td><?php echo $this->escapeHtml($movie->endDate);?></td>
    <td><?php echo $this->escapeHtml($movie->cinemaName);?></td>
    <td><?php echo $this->escapeHtml($movie->category);?></td>
    <?php if ($this->auth()->isAllowed('movie_edit')) { ?>
    <td>
        <a href="<?php echo $this->url('movie',
            array('action'=>'edit', 'id' => $movie->id));?>">
            <img src="<?= $this->basePath('img/edit.png') ?>" height="20" alt="Edit"/>
        </a>
        <a href="<?php echo $this->url('movie',
            array('action'=>'delete', 'id' => $movie->id));?>">
            <img src="<?= $this->basePath('img/delete.jpg') ?>" height="20" alt="Delete"/>
        </a>
    </td>
    <?php } ?>
</tr>
<?php endforeach; ?>
</table>
